# Generated by Django 3.0.11 on 2020-11-28 21:34

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20201128_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('percentage_on_salary', models.DecimalField(decimal_places=2, default=20, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('percentage_of_the_plan', models.DecimalField(decimal_places=2, default=100, max_digits=8, validators=[django.core.validators.MinValueValidator(100)])),
                ('is_bankoffice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(default=datetime.datetime(2020, 11, 28, 21, 34, 22, 500726, tzinfo=utc))),
                ('date_to', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general_plan', models.BooleanField(default=False)),
                ('indicator_name', models.CharField(max_length=150)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_from', models.DateTimeField(default=datetime.datetime(2020, 11, 28, 21, 34, 22, 500089, tzinfo=utc))),
                ('date_to', models.DateTimeField()),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KPIs', to='plans.Formula')),
                ('formula_bankoffice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KPIs_b', to='plans.Formula')),
            ],
            options={
                'unique_together': {('formula', 'formula_bankoffice')},
            },
        ),
        migrations.CreateModel(
            name='ManagerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('KPI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_plans', to='plans.KPI')),
                ('general_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_plans', to='plans.GeneralPlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('KPI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_kpis', to='plans.KPI')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_kpis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPIitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_items', to='plans.KPI')),
                ('general_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_items', to='plans.GeneralPlan')),
            ],
        ),
        migrations.CreateModel(
            name='BankOfficePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('KPI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_plans', to='plans.KPI')),
                ('bankoffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_plans', to='users.BankOffice')),
                ('general_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_plans', to='plans.GeneralPlan')),
            ],
        ),
        migrations.CreateModel(
            name='BankOfficeKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('KPI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_kpis', to='plans.KPI')),
                ('bankoffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_kpis', to='users.BankOffice')),
            ],
        ),
    ]
