# Generated by Django 3.0.11 on 2020-11-23 21:42

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankOfficePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('percentage_on_salary', models.DecimalField(decimal_places=2, default=20, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('percentage_of_the_plan', models.DecimalField(decimal_places=2, default=100, max_digits=8, validators=[django.core.validators.MinValueValidator(100)])),
                ('type_result', models.NullBooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(default=datetime.datetime(2020, 11, 23, 21, 42, 11, 632195, tzinfo=utc))),
                ('date_to', models.DateTimeField()),
                ('KPI_target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='KPIitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('KPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_plans', to='plans.KPI')),
                ('general_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_plans', to='plans.GeneralPlan')),
            ],
        ),
    ]
