# Generated by Django 3.0.11 on 2020-11-18 14:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20201116_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(default=datetime.datetime(2020, 11, 18, 16, 40, 47, 415079))),
                ('date_to', models.DateTimeField()),
                ('KPI_target_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('KPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_plans', to='plans.KPI')),
                ('general_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_plans', to='plans.GeneralPlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='generalplan',
            name='KPI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generals_plans', to='plans.KPI'),
        ),
        migrations.CreateModel(
            name='BankOfficePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('KPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffices_plans', to='plans.KPI')),
                ('bankoffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffices_plans', to='users.BankOffice')),
                ('general_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffices_plans', to='plans.GeneralPlan')),
            ],
        ),
    ]
