# Generated by Django 3.0.11 on 2020-11-25 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerkpi',
            name='KPI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_kpis', to='plans.KPI'),
        ),
        migrations.AddField(
            model_name='managerkpi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_kpis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KPIs', to='plans.Formula'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='formula_bankoffice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KPIs_b', to='plans.Formula'),
        ),
        migrations.AddField(
            model_name='generalplan',
            name='KPI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generals_plans', to='plans.KPI'),
        ),
        migrations.AddField(
            model_name='bankofficeplan',
            name='KPI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_plans', to='plans.KPI'),
        ),
        migrations.AddField(
            model_name='bankofficeplan',
            name='bankoffice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_plans', to='users.BankOffice'),
        ),
        migrations.AddField(
            model_name='bankofficeplan',
            name='general_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_plans', to='plans.GeneralPlan'),
        ),
        migrations.AddField(
            model_name='bankofficekpi',
            name='KPI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_kpis', to='plans.KPI'),
        ),
        migrations.AddField(
            model_name='bankofficekpi',
            name='bankoffice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_kpis', to='users.BankOffice'),
        ),
        migrations.AlterUniqueTogether(
            name='kpi',
            unique_together={('formula', 'formula_bankoffice')},
        ),
    ]
