# Generated by Django 3.0.11 on 2020-11-23 22:42

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20201123_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalplan',
            name='KPI_target_amount',
        ),
        migrations.AddField(
            model_name='kpi',
            name='KPI_target_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='kpi',
            name='date_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 23, 22, 42, 45, 338117, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalplan',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 22, 42, 45, 338583, tzinfo=utc)),
        ),
    ]
