# Generated by Django 3.0.11 on 2020-11-25 23:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20201126_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 23, 36, 45, 359654, tzinfo=utc)),
        ),
    ]
