# Generated by Django 3.0.11 on 2020-11-23 23:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20201124_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpi',
            old_name='KPI_target_amount',
            new_name='target_amount',
        ),
        migrations.AlterField(
            model_name='generalplan',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 23, 24, 24, 863842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='date_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 23, 23, 24, 24, 863364, tzinfo=utc), null=True),
        ),
    ]
