# Generated by Django 3.0.11 on 2020-11-18 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201118_1742'),
        ('plans', '0003_auto_20201118_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankofficeplan',
            name='KPI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_plans', to='plans.KPI'),
        ),
        migrations.AlterField(
            model_name='bankofficeplan',
            name='bankoffice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_plans', to='users.BankOffice'),
        ),
        migrations.AlterField(
            model_name='bankofficeplan',
            name='general_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_plans', to='plans.GeneralPlan'),
        ),
        migrations.AlterField(
            model_name='generalplan',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 17, 42, 20, 590116)),
        ),
    ]
