# Generated by Django 3.0.11 on 2020-11-25 23:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20201126_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 23, 47, 40, 980436, tzinfo=utc)),
        ),
    ]
