# Generated by Django 3.0.11 on 2020-11-23 23:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20201124_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='type_result',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='date_to',
        ),
        migrations.AddField(
            model_name='formula',
            name='is_bankoffice',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='generalplan',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 23, 43, 55, 50431, tzinfo=utc)),
        ),
    ]
