# Generated by Django 3.0.11 on 2020-11-26 00:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20201126_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='is_general_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 0, 31, 47, 27580, tzinfo=utc)),
        ),
    ]
