# Generated by Django 3.0.11 on 2020-11-30 01:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20201129_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalplan',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 1, 3, 19, 69221, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 1, 3, 19, 68660, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KPI_f', to='plans.Formula'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='formula_bankoffice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KPI_fb', to='plans.Formula'),
        ),
        migrations.AlterUniqueTogether(
            name='kpi',
            unique_together=set(),
        ),
    ]
