# Generated by Django 3.0.11 on 2020-11-26 00:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_auto_20201126_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalplan',
            name='KPI',
        ),
        migrations.AddField(
            model_name='generalplan',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 0, 42, 19, 189840, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='generalplan',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 0, 42, 19, 189840, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpi',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 0, 42, 19, 189228, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='KPIitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_items', to='plans.KPI')),
                ('general_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_items', to='plans.GeneralPlan')),
            ],
        ),
    ]
