# Generated by Django 3.0.11 on 2020-11-23 23:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_auto_20201124_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='formula_bankoffice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KPIs_b', to='plans.Formula'),
        ),
        migrations.AlterField(
            model_name='generalplan',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 23, 54, 18, 597010, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='kpi',
            unique_together={('formula', 'formula_bankoffice')},
        ),
    ]
