# Generated by Django 3.0.11 on 2020-11-24 00:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20201124_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='is_bankoffice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generalplan',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 0, 1, 48, 975700, tzinfo=utc)),
        ),
    ]
