# Generated by Django 3.0.11 on 2020-11-24 00:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20201124_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankofficeplan',
            name='KPI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankoffice_plans', to='plans.KPI'),
        ),
        migrations.AlterField(
            model_name='bankofficeplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='generalplan',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 0, 12, 17, 165382, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='managerplan',
            name='KPI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_plans', to='plans.KPI'),
        ),
        migrations.AlterField(
            model_name='managerplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='KPIitem',
        ),
    ]
