# Generated by Django 3.0.11 on 2020-11-24 00:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_auto_20201124_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalplan',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 0, 38, 31, 762997, tzinfo=utc)),
        ),
    ]
