# Generated by Django 3.0.11 on 2020-11-24 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_auto_20201124_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalplan',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 0, 39, 54, 316412, tzinfo=utc)),
        ),
    ]
