# Generated by Django 3.0.11 on 2020-11-24 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_auto_20201124_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalplan',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='generalplan',
            name='date_to',
        ),
        migrations.AddField(
            model_name='kpi',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 15, 14, 26, 745938, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='kpi',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 15, 14, 26, 745938, tzinfo=utc)),
            preserve_default=False,
        ),
    ]

