# Generated by Django 3.0.11 on 2020-11-16 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.BankOffice'),
            preserve_default=False,
        ),
    ]
