# Generated by Django 3.0.11 on 2020-11-25 23:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201126_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 23, 47, 40, 976436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='premia',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 23, 47, 40, 976436, tzinfo=utc)),
        ),
    ]
