# Generated by Django 3.0.11 on 2020-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201116_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankoffice',
            name='number',
        ),
        migrations.AlterField(
            model_name='bankoffice',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bankoffice',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bankoffice',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
