# Generated by Django 3.0.11 on 2020-11-29 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201129_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('process', 'process')], default='process', max_length=20),
        ),
        migrations.AddField(
            model_name='premium',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('process', 'process')], default='process', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 18, 1, 58, 504473, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='premium',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 18, 1, 58, 504473, tzinfo=utc)),
        ),
    ]
