# Generated by Django 3.0.11 on 2020-11-29 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201129_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 18, 33, 38, 134582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='premium',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 18, 33, 38, 134582, tzinfo=utc)),
        ),
    ]
