# Generated by Django 3.0.11 on 2020-11-30 01:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201129_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 1, 3, 19, 65099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='premium',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 1, 3, 19, 65099, tzinfo=utc)),
        ),
    ]
