# Generated by Django 3.0.11 on 2020-11-26 01:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201126_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='integration_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 1, 10, 25, 708894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='premium',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 1, 10, 25, 708894, tzinfo=utc)),
        ),
    ]
