# Generated by Django 3.0.11 on 2020-11-26 01:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201126_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 1, 16, 10, 532846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='premium',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 1, 16, 10, 532846, tzinfo=utc)),
        ),
    ]
