# Generated by Django 3.0.11 on 2020-11-25 23:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0003_auto_20201126_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KPl_result_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('KPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_daily', to='plans.KPI')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_daily', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
