# Generated by Django 3.0.11 on 2020-11-26 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_roles', '0002_auto_20201126_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultitem',
            old_name='KPl_result_amount',
            new_name='KPI_result_amount',
        ),
    ]
