# Generated by Django 3.0.11 on 2020-11-26 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager_roles', '0003_auto_20201126_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdaily',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_dailys', to=settings.AUTH_USER_MODEL),
        ),
    ]
