# Generated by Django 3.0.11 on 2020-11-27 00:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manager_roles', '0004_auto_20201127_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdaily',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 0, 11, 3, 774918, tzinfo=utc)),
        ),
    ]
